insert into dc.automaker (id, country, name) values (1, 'Japan', 'Honda');
insert into dc.automaker (id, country, name) values (2, 'Japan', 'Toyota');
insert into dc.automaker (id, country, name) values (3, 'Japan', 'Nissan');
insert into dc.automaker (id, country, name) values (4, 'Japan', 'Datsun');
insert into dc.automaker (id, country, name) values (5, 'Japan', 'Subaru');
insert into dc.automaker (id, country, name) values (6, 'Japan', 'Mitsubishi');
insert into dc.automaker (id, country, name) values (7, 'Japan', 'Acura');
insert into dc.automaker (id, country, name) values (8, 'Japan', 'Lexus');
insert into dc.automaker (id, country, name) values (9, 'United States', 'Ford');
insert into dc.automaker (id, country, name) values (10, 'United States', 'Chevrolet');
insert into dc.automaker (id, country, name) values (11, 'United States', 'Dodge');
insert into dc.automaker (id, country, name) values (12, 'United States', 'Jeep');
insert into dc.automaker (id, country, name) values (13, 'United States', 'Chrysler');
insert into dc.automaker (id, country, name) values (14, 'United States', 'Cadillac');
insert into dc.automaker (id, country, name) values (15, 'United States', 'Pontiac');
insert into dc.automaker (id, country, name) values (16, 'France', 'Renault');
insert into dc.automaker (id, country, name) values (17, 'France', 'Peugeot');
insert into dc.automaker (id, country, name) values (18, 'France', 'Citroen');
insert into dc.automaker (id, country, name) values (19, 'France', 'Alpine');
insert into dc.automaker (id, country, name) values (20, 'Germany', 'Volkswagen');
insert into dc.automaker (id, country, name) values (21, 'Germany', 'Porsche');
insert into dc.automaker (id, country, name) values (22, 'Germany', 'BMW');
insert into dc.automaker (id, country, name) values (23, 'Germany', 'Mercedes Benz');
insert into dc.automaker (id, country, name) values (24, 'England', 'McLaren');
insert into dc.automaker (id, country, name) values (25, 'England', 'Jaguar');
insert into dc.automaker (id, country, name) values (26, 'United States', 'Tesla');
insert into dc.automaker (id, country, name) values (27, 'Italy', 'Lamborghini');
insert into dc.automaker (id, country, name) values (28, 'England', 'Land Rover');
insert into dc.automaker (id, country, name) values (29, 'England', 'Mini');
insert into dc.automaker (id, country, name) values (30, 'Italy', 'Ducati');